name: Testing workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: "Run unittest"
        run: python -m unittest
      - name: "run coverage"
        run: python -m coverage run -m unittest tests/unit/test_diffusion2d_functions.py

  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
