name: Testing workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10' 
      - name: install pip
        run: python -m ensurepip --upgrade
      - name: install packages
        run: pip install coverage numpy matplotlib pytest
      - name: "run coverage"
        run: coverage run -m pytest
      - name: "generate report"
        run: coverage report -m >> .coverage
      - name: keep report
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: .coverage
          retention-days: 1
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
