name: Testing workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          cache: 'pip' # caching pip dependencies
      - name: install packages
        run: pip install coverage numpy matplotlib
      - name: "Run unittest"
        run: python -m unittest
      - name: "run coverage"
        run: python -m coverage run -m unittest tests/unit/test_diffusion2d_functions.py
      - name: "generate report"
        run: python -m coverage report

  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
